version: "3.8"

services:

  main:
    build: .
    command: sh -c "python main.py"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
  web:
    build: .
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  scrap:
    build: .
    command: sh -c "python scrap.py"
    volumes:
      - .:/code
